#import <Foundation/Foundation.h>
#import "INVObject.h"

/**
* InventoryAPI
* Orkiv Inventory API client 
*
* OpenAPI spec version: 1.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/



@protocol INVOrderRequest
@end

@interface INVOrderRequest : INVObject

/* Order ID [optional]
 */
@property(nonatomic) NSString* orderId;
/* Customer email [optional]
 */
@property(nonatomic) NSString* infoEmail;
/* Customer first name [optional]
 */
@property(nonatomic) NSString* infoFirst;
/* Customer last name [optional]
 */
@property(nonatomic) NSString* infoLast;
/* Customer phone number [optional]
 */
@property(nonatomic) NSString* phone;
/* Customer billing address matches shipping address [optional]
 */
@property(nonatomic) NSNumber* shipset;
/* Customer billing address line '1' [optional]
 */
@property(nonatomic) NSString* infoAdr1;
/* Customer billing address line '2' [optional]
 */
@property(nonatomic) NSString* infoAdr2;
/* Customer billing city [optional]
 */
@property(nonatomic) NSString* infoCty;
/* Customer billing zip code [optional]
 */
@property(nonatomic) NSString* infoZip;
/* Customer billing state [optional]
 */
@property(nonatomic) NSString* state;
/* Customer shipping address line '1' [optional]
 */
@property(nonatomic) NSString* infoSadr1;
/* Customer shipping address line '2' [optional]
 */
@property(nonatomic) NSString* infoSadr2;
/* Customer shipping city [optional]
 */
@property(nonatomic) NSString* infoScty;
/* Customer shipping zip code [optional]
 */
@property(nonatomic) NSString* infoSzip;
/* Customer shipping state [optional]
 */
@property(nonatomic) NSString* sstate;
/* Tax amount in hundreds. Must divide by '100' for USD value [optional]
 */
@property(nonatomic) NSNumber* taxAmount;
/* Shipping total in USD [optional]
 */
@property(nonatomic) NSNumber* shippingAmount;
/* Checkout total in USD [optional]
 */
@property(nonatomic) NSNumber* amountTotal;

@end
